esphome:
  name: sm

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

i2c:
  - id: bus_a
    sda: GPIO7
    scl: GPIO9
    frequency: 800kHz

uart:
  rx_pin: GPIO20
  tx_pin: GPIO21
  baud_rate: 9600

# buttons
binary_sensor:
  - platform: gpio
    id: top
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
  - platform: gpio
    id: left
    pin:
      number: GPIO1
      mode:
        input: true
        pullup: true
  - platform: gpio
    id: bottom
    pin:
      number: GPIO2
      mode:
        input: true
        pullup: true
  - platform: gpio
    id: right
    pin:
      number: GPIO3
      mode:
        input: true
        pullup: true
  - platform: gpio
    id: press
    pin:
      number: GPIO4
      mode:
        input: true
        pullup: true

sensor:
  - platform: senseair
    co2:
      name: "SenseAir CO2 Value"
      id: senseair_co2
    update_interval: 10s
    id: senseair_s8
  - platform: bme680
    i2c_id: bus_a
    temperature:
      name: "BME680 Temperature"
      id: temp
      oversampling: 16x
    pressure:
      id: pressure
      name: "BME680 Pressure"
    humidity:
      id: humidity
      name: "BME680 Humidity"
    gas_resistance:
      name: "BME680 Gas Resistance"
      id: gas
    address: 0x77
    update_interval: 60s

output:
  - platform: gpio
    pin: GPIO8
    id: gpio_led

font:
  - file: "/usr/share/fonts/truetype/terminus/TerminusTTF-4.46.0.ttf"
    id: large_font
    size: 32
  - file: "/usr/share/fonts/truetype/terminus/TerminusTTF-4.46.0.ttf"
    id: medium_font
    size: 20
  - file: "/usr/share/fonts/truetype/terminus/TerminusTTF-4.46.0.ttf"
    id: small_font
    size: 14

display:
  - platform: ssd1306_i2c
    brightness: 100%
    model: "SSD1306 128x64"
    address: 0x3C
    i2c_id: bus_a
    id: my_display
    lambda: |-
      it.print(0, 4, id(medium_font), COLOR_ON, "CO");
      it.print(20, 10, id(small_font), COLOR_ON, "2");
      it.printf(75, 14, id(large_font), COLOR_ON, TextAlign::CENTER, "%.0f", id(senseair_co2).state);
      it.printf(0, 28, id(medium_font), COLOR_ON, "%.0f°C %.0f%%", id(temp).state, id(humidity).state);
      it.printf(0, 50, id(small_font), COLOR_ON, "%.0fhPa", id(pressure).state);

